# Generated by Django 2.1.1 on 2018-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'manages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketBookings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=45)),
                ('l_name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=45)),
                ('date_of_visit', models.DateField()),
                ('city', models.CharField(max_length=45)),
                ('no_of_adult_tickets', models.IntegerField()),
                ('no_of_child_tickets', models.IntegerField()),
            ],
            options={
                'db_table': 'ticket_bookings',
                'managed': False,
            },
        ),
    ]
