# Generated by Django 2.1.1 on 2018-10-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0002_manages_ticketbookings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exhibit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='livesin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='looksafter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticketbookings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worksin',
            options={},
        ),
    ]
